var lbl_shortDayNames = ["星期天", "星期一", "星期二", "星期三", "星期四", "星期五", "星期六"];
var lbl_fullDayNames = ["星期天", "星期一", "星期二", "星期三", "星期四", "星期五", "星期六"];
var lbl_titleContentDateTime = "時間設置";
var lbl_setButtonContent = "設置";
var lbl_clearButtonContent = "取消";

var countryCode = [
{countryName:'安哥拉',countryCode:'244'},
{countryName:'阿富汗',countryCode:'93'},
{countryName:'阿爾巴尼亞',countryCode:'355'},
{countryName:'阿爾及利亞',countryCode:'213'},
{countryName:'安道爾共和國',countryCode:'376'},
{countryName:'安圭拉島',countryCode:'1264'},
{countryName:'安提瓜和巴布達',countryCode:'1268'},
{countryName:'阿根廷',countryCode:'54'},
{countryName:'亞美尼亞',countryCode:'374'},
{countryName:'阿森松',countryCode:'247'},
{countryName:'澳大利亞',countryCode:'61'},
{countryName:'奧地利',countryCode:'43'},
{countryName:'阿塞拜疆',countryCode:'994'},
{countryName:'巴哈馬',countryCode:'1242'},
{countryName:'巴林',countryCode:'973'},
{countryName:'孟加拉',countryCode:'880'},
{countryName:'巴巴多斯',countryCode:'1246'},
{countryName:'白俄羅斯',countryCode:'375'},
{countryName:'比利時',countryCode:'32'},
{countryName:'伯利茲',countryCode:'501'},
{countryName:'貝寧',countryCode:'229'},
{countryName:'百慕大群島',countryCode:'1441'},
{countryName:'玻利維亞',countryCode:'591'},
{countryName:'博茨瓦納',countryCode:'267'},
{countryName:'巴西',countryCode:'55'},
{countryName:'汶萊',countryCode:'673'},
{countryName:'保加利亞 ',countryCode:'359'},
{countryName:'布基納法索',countryCode:'226'},
{countryName:'緬甸',countryCode:'95'},
{countryName:'布隆迪',countryCode:'257'},
{countryName:'喀麥隆',countryCode:'237'},
{countryName:'加拿大',countryCode:'1'},
{countryName:'開曼群島',countryCode:'1345'},
{countryName:'中非共和國',countryCode:'236'},
{countryName:'乍得',countryCode:'235'},
{countryName:'智利',countryCode:'56'},
{countryName:'中國',countryCode:'86'},
{countryName:'哥倫比亞',countryCode:'57'},
{countryName:'剛果',countryCode:'242'},
{countryName:'庫克群島',countryCode:'682'},
{countryName:'哥斯大黎加',countryCode:'506'},
{countryName:'古巴',countryCode:'53'},
{countryName:'賽普勒斯',countryCode:'357'},
{countryName:'捷克',countryCode:'420'},
{countryName:'丹麥',countryCode:'45'},
{countryName:'吉布提 ',countryCode:'253'},
{countryName:'多明尼加共和國 1849',countryCode:'1849'},
{countryName:'多明尼加共和國 1809',countryCode:'1809'},
{countryName:'多明尼加共和國 1829',countryCode:'1829'},
{countryName:'厄瓜多爾',countryCode:'593'},
{countryName:'埃及',countryCode:'20'},
{countryName:'薩爾瓦多',countryCode:'503'},
{countryName:'愛沙尼亞',countryCode:'372'},
{countryName:'埃塞俄比亞',countryCode:'251'},
{countryName:'斐濟',countryCode:'679'},
{countryName:'芬蘭',countryCode:'358'},
{countryName:'法國',countryCode:'33'},
{countryName:'法屬圭亞那',countryCode:'594'},
{countryName:'加蓬',countryCode:'241'},
{countryName:'岡比亞',countryCode:'220'},
{countryName:'格魯吉亞',countryCode:'995'},
{countryName:'德國',countryCode:'49'},
{countryName:'加納',countryCode:'233'},
{countryName:'直布羅陀',countryCode:'350'},
{countryName:'希臘',countryCode:'30'},
{countryName:'格林納達',countryCode:'1809'},
{countryName:'關島',countryCode:'1671'},
{countryName:'瓜地馬拉',countryCode:'502'},
{countryName:'幾內亞',countryCode:'224'},
{countryName:'圭亞那',countryCode:'592'},
{countryName:'海地',countryCode:'509'},
{countryName:'洪都拉斯',countryCode:'504'},
{countryName:'香港',countryCode:'852'},
{countryName:'匈牙利',countryCode:'36'},
{countryName:'冰島',countryCode:'354'},
{countryName:'印度',countryCode:'91'},
{countryName:'印尼',countryCode:'62'},
{countryName:'伊朗',countryCode:'98'},
{countryName:'伊拉克',countryCode:'964'},
{countryName:'愛爾蘭',countryCode:'353'},
{countryName:'以色列',countryCode:'972'},
{countryName:'義大利',countryCode:'39'},
{countryName:'象牙海岸',countryCode:'225'},
{countryName:'牙買加',countryCode:'1876'},
{countryName:'日本',countryCode:'81'},
{countryName:'約旦',countryCode:'962'},
{countryName:'柬埔寨',countryCode:'855'},
{countryName:'哈薩克斯坦',countryCode:'327'},
{countryName:'肯雅',countryCode:'254'},
{countryName:'韓國',countryCode:'82'},
{countryName:'科威特',countryCode:'965'},
{countryName:'吉爾吉斯坦',countryCode:'331'},
{countryName:'老撾',countryCode:'856'},
{countryName:'拉脫維亞',countryCode:'371'},
{countryName:'黎巴嫩',countryCode:'961'},
{countryName:'萊索托',countryCode:'266'},
{countryName:'尼伯爾',countryCode:'977'},
{countryName:'瑙魯',countryCode:'674'},
{countryName:'納米比亞',countryCode:'264'},
{countryName:'莫三比克',countryCode:'258'},
{countryName:'摩洛哥',countryCode:'212'},
{countryName:'蒙特塞拉特島',countryCode:'1664'},
{countryName:'蒙古',countryCode:'976'},
{countryName:'摩納哥',countryCode:'377'},
{countryName:'莫爾達瓦',countryCode:'373'},
{countryName:'墨西哥',countryCode:'52'},
{countryName:'毛里求斯',countryCode:'230'},
{countryName:'馬提尼克',countryCode:'596'},
{countryName:'馬里亞那群島',countryCode:'1670'},
{countryName:'馬爾他',countryCode:'356'},
{countryName:'馬里',countryCode:'223'},
{countryName:'馬爾代夫',countryCode:'960'},
{countryName:'馬來西亞',countryCode:'60'},
{countryName:'馬拉維',countryCode:'265'},
{countryName:'馬達加斯加',countryCode:'261'},
{countryName:'澳門',countryCode:'853'},
{countryName:'盧森堡',countryCode:'352'},
{countryName:'立陶宛',countryCode:'370'},
{countryName:'列支敦士登',countryCode:'423'},
{countryName:'利比亞',countryCode:'218'},
{countryName:'利比理亞',countryCode:'231'},
{countryName:'荷屬安的列斯',countryCode:'599'},
{countryName:'荷蘭',countryCode:'31'},
{countryName:'新西蘭',countryCode:'64'},
{countryName:'尼加拉瓜',countryCode:'505'},
{countryName:'尼日爾',countryCode:'227'},
{countryName:'尼日利亞',countryCode:'234'},
{countryName:'朝鮮',countryCode:'850'},
{countryName:'挪威',countryCode:'47'},
{countryName:'阿曼',countryCode:'968'},
{countryName:'巴基斯坦',countryCode:'92'},
{countryName:'巴拿馬',countryCode:'507'},
{countryName:'巴布亞新幾內亞',countryCode:'675'},
{countryName:'巴拉圭',countryCode:'595'},
{countryName:'秘魯',countryCode:'51'},
{countryName:'菲律賓',countryCode:'63'},
{countryName:'波蘭',countryCode:'48'},
{countryName:'法屬玻利尼西亞',countryCode:'689'},
{countryName:'葡萄牙',countryCode:'351'},
{countryName:'波多黎各',countryCode:'1787'},
{countryName:'卡塔爾',countryCode:'974'},
{countryName:'留尼旺 ',countryCode:'262'},
{countryName:'羅馬尼亞',countryCode:'40'},
{countryName:'俄羅斯',countryCode:'7'},
{countryName:'聖盧西亞',countryCode:'1758'},
{countryName:'聖文森特島',countryCode:'1784'},
{countryName:'東薩摩亞(美）',countryCode:'684'},
{countryName:'西薩摩亞',countryCode:'685'},
{countryName:'聖馬力諾',countryCode:'378'},
{countryName:'聖多美和普林西比',countryCode:'239'},
{countryName:'沙烏地阿拉伯',countryCode:'966'},
{countryName:'塞內加爾',countryCode:'221'},
{countryName:'塞舌耳',countryCode:'248'},
{countryName:'塞拉里昂',countryCode:'232'},
{countryName:'新加坡',countryCode:'65'},
{countryName:'斯洛伐克',countryCode:'421'},
{countryName:'斯洛文尼亞',countryCode:'386'},
{countryName:'所羅門群島',countryCode:'677'},
{countryName:'索馬里',countryCode:'252'},
{countryName:'南非',countryCode:'27'},
{countryName:'西班牙',countryCode:'34'},
{countryName:'斯里蘭卡',countryCode:'94'},
{countryName:'聖盧西亞',countryCode:'1758'},
{countryName:'聖文森特',countryCode:'1784'},
{countryName:'蘇丹',countryCode:'249'},
{countryName:'蘇里南',countryCode:'597'},
{countryName:'斯威士蘭',countryCode:'268'},
{countryName:'瑞典',countryCode:'46'},
{countryName:'瑞士',countryCode:'41'},
{countryName:'敘利亞',countryCode:'963'},
{countryName:'臺灣省',countryCode:'886'},
{countryName:'塔吉克斯坦',countryCode:'992'},
{countryName:'坦桑尼亞',countryCode:'255'},
{countryName:'泰國',countryCode:'66'},
{countryName:'多哥',countryCode:'228'},
{countryName:'湯加',countryCode:'676'},
{countryName:'特立尼達和多巴哥',countryCode:'1809'},
{countryName:'突尼斯',countryCode:'216'},
{countryName:'土耳其',countryCode:'90'},
{countryName:'土庫曼斯坦',countryCode:'993'},
{countryName:'烏干達',countryCode:'256'},
{countryName:'烏克蘭',countryCode:'380'},
{countryName:'阿拉伯聯合酋長國',countryCode:'971'},
{countryName:'英國',countryCode:'44'},
{countryName:'美國',countryCode:'1'},
{countryName:'烏拉圭',countryCode:'598'},
{countryName:'烏茲別克斯坦',countryCode:'233'},
{countryName:'委內瑞拉',countryCode:'58'},
{countryName:'越南',countryCode:'84'},
{countryName:'葉門',countryCode:'967'},
{countryName:'南斯拉夫',countryCode:'381'},
{countryName:'南非',countryCode:'27'},
{countryName:'辛巴威',countryCode:'263'},
{countryName:'薩伊',countryCode:'243'},
{countryName:'尚比亞',countryCode:'260'}
];

var error_msg = [
    {code:'10016',msg:'用戶不存在'},
    {code:'10104',msg:'驗證碼錯誤'},
    {code:'30315',msg:'參數錯誤'},
    {code:'30501',msg:'郵箱已註冊'},
    {code:'30502',msg:'郵箱格式錯誤'},
    {code:'30504',msg:'郵件發送失敗'}
]
var error_str = "錯誤碼：";

var mail_str="郵箱";
var platform_str="廠商";
var newpassword_notequest_confirmedpassword="新密碼與確認密碼不一致";
var not_null="不能為空!";
var lack_of_length="密碼必須是字母+數字的組合，且長度要在8-10位之間";
