var lbl_shortDayNames = ["Sun.", "Mon.", "Tues.", "Wed.", "Thur.", "Fri.", "Sat."];
var lbl_fullDayNames = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
var lbl_titleContentDateTime = "Time Setting";
var lbl_setButtonContent = "OK";
var lbl_clearButtonContent = "Cancel";


var countryCode = [
{countryName:'Angola',countryCode:'244'},
{countryName:'Afghanistan',countryCode:'93'},
{countryName:'Albania',countryCode:'355'},
{countryName:'Algeria',countryCode:'213'},
{countryName:'Andorra',countryCode:'376'},
{countryName:'Anguilla',countryCode:'1264'},
{countryName:'Antigua and Barbuda',countryCode:'1268'},
{countryName:'Argentina',countryCode:'54'},
{countryName:'Armenia',countryCode:'374'},
{countryName:'Ascension',countryCode:'247'},
{countryName:'Australia',countryCode:'61'},
{countryName:'Austria',countryCode:'43'},
{countryName:'Azerbaijan',countryCode:'994'},
{countryName:'Bahamas',countryCode:'1242'},
{countryName:'Bahrain',countryCode:'973'},
{countryName:'Bangladesh',countryCode:'880'},
{countryName:'Barbados',countryCode:'1246'},
{countryName:'Belarus',countryCode:'375'},
{countryName:'Belgium',countryCode:'32'},
{countryName:'Belize',countryCode:'501'},
{countryName:'Benin',countryCode:'229'},
{countryName:'Bermuda',countryCode:'1441'},
{countryName:'Bolivia',countryCode:'591'},
{countryName:'Botswana',countryCode:'267'},
{countryName:'Brazil',countryCode:'55'},
{countryName:'Brunei',countryCode:'673'},
{countryName:'Bulgaria ',countryCode:'359'},
{countryName:'Burkina Faso',countryCode:'226'},
{countryName:'Myanmar',countryCode:'95'},
{countryName:'Burundi',countryCode:'257'},
{countryName:'Cameroon',countryCode:'237'},
{countryName:'Canada',countryCode:'1'},
{countryName:'Cayman Islands',countryCode:'1345'},
{countryName:'Central African Republic',countryCode:'236'},
{countryName:'Chad',countryCode:'235'},
{countryName:'Chile',countryCode:'56'},
{countryName:'China',countryCode:'86'},
{countryName:'Colombia',countryCode:'57'},
{countryName:'Congo',countryCode:'242'},
{countryName:'Cook Islands',countryCode:'682'},
{countryName:'Costa Rica',countryCode:'506'},
{countryName:'Cuba',countryCode:'53'},
{countryName:'Cyprus',countryCode:'357'},
{countryName:'Czech Republic',countryCode:'420'},
{countryName:'Denmark',countryCode:'45'},
{countryName:'Djibouti ',countryCode:'253'},
{countryName:'Dominica 1849',countryCode:'1849'},
{countryName:'Dominica 1809',countryCode:'1809'},
{countryName:'Dominica 1829',countryCode:'1829'},
{countryName:'Ecuador',countryCode:'593'},
{countryName:'Egypt',countryCode:'20'},
{countryName:'El Salvador',countryCode:'503'},
{countryName:'Estonia',countryCode:'372'},
{countryName:'Ethiopia',countryCode:'251'},
{countryName:'Fiji',countryCode:'679'},
{countryName:'Finland',countryCode:'358'},
{countryName:'France',countryCode:'33'},
{countryName:'French Guiana',countryCode:'594'},
{countryName:'Gabon',countryCode:'241'},
{countryName:'Gambia',countryCode:'220'},
{countryName:'Georgia',countryCode:'995'},
{countryName:'Germany',countryCode:'49'},
{countryName:'Ghana',countryCode:'233'},
{countryName:'Gibraltar',countryCode:'350'},
{countryName:'Greece',countryCode:'30'},
{countryName:'Grenada',countryCode:'1809'},
{countryName:'Guam',countryCode:'1671'},
{countryName:'Guatemala',countryCode:'502'},
{countryName:'Guinea',countryCode:'224'},
{countryName:'Guyana',countryCode:'592'},
{countryName:'Haiti',countryCode:'509'},
{countryName:'Honduras',countryCode:'504'},
{countryName:'Hong Kong',countryCode:'852'},
{countryName:'Hungary',countryCode:'36'},
{countryName:'Iceland',countryCode:'354'},
{countryName:'India',countryCode:'91'},
{countryName:'Indonesia',countryCode:'62'},
{countryName:'Iran',countryCode:'98'},
{countryName:'Iraq',countryCode:'964'},
{countryName:'Ireland',countryCode:'353'},
{countryName:'Israel',countryCode:'972'},
{countryName:'Italy',countryCode:'39'},
{countryName:'Cote d\'Ivoire',countryCode:'225'},
{countryName:'Jamaica',countryCode:'1876'},
{countryName:'Japan',countryCode:'81'},
{countryName:'Jordan',countryCode:'962'},
{countryName:'Cambodia',countryCode:'855'},
{countryName:'Kazakhstan',countryCode:'327'},
{countryName:'Kenya',countryCode:'254'},
{countryName:'Korea',countryCode:'82'},
{countryName:'Kuwait',countryCode:'965'},
{countryName:'Kyrgyzstan',countryCode:'331'},
{countryName:'Laos',countryCode:'856'},
{countryName:'Latvia',countryCode:'371'},
{countryName:'Lebanon',countryCode:'961'},
{countryName:'Lesotho',countryCode:'266'},
{countryName:'Nepal',countryCode:'977'},
{countryName:'Nauru',countryCode:'674'},
{countryName:'Namibia',countryCode:'264'},
{countryName:'Mozambique',countryCode:'258'},
{countryName:'Morocco',countryCode:'212'},
{countryName:'Montserrat',countryCode:'1664'},
{countryName:'Mongolia',countryCode:'976'},
{countryName:'Monaco',countryCode:'377'},
{countryName:'Moldova',countryCode:'373'},
{countryName:'Mexico',countryCode:'52'},
{countryName:'Mauritius',countryCode:'230'},
{countryName:'Martinique',countryCode:'596'},
{countryName:'Mariana Islands',countryCode:'1670'},
{countryName:'Malta',countryCode:'356'},
{countryName:'Mali',countryCode:'223'},
{countryName:'Maldives',countryCode:'960'},
{countryName:'Malaysia',countryCode:'60'},
{countryName:'Malawi',countryCode:'265'},
{countryName:'Madagascar',countryCode:'261'},
{countryName:'Macau',countryCode:'853'},
{countryName:'Luxembourg',countryCode:'352'},
{countryName:'Lithuania',countryCode:'370'},
{countryName:'Liechtenstein',countryCode:'423'},
{countryName:'Libya',countryCode:'218'},
{countryName:'Liberia',countryCode:'231'},
{countryName:'Netherlands Antilles',countryCode:'599'},
{countryName:'Netherlands',countryCode:'31'},
{countryName:'New Zealand',countryCode:'64'},
{countryName:'Nicaragua',countryCode:'505'},
{countryName:'Niger',countryCode:'227'},
{countryName:'Nigeria',countryCode:'234'},
{countryName:'North Korea',countryCode:'850'},
{countryName:'Norway',countryCode:'47'},
{countryName:'Oman',countryCode:'968'},
{countryName:'Pakistan',countryCode:'92'},
{countryName:'Panama',countryCode:'507'},
{countryName:'Papua New Guinea',countryCode:'675'},
{countryName:'Paraguay',countryCode:'595'},
{countryName:'Peru',countryCode:'51'},
{countryName:'Philippines',countryCode:'63'},
{countryName:'Poland',countryCode:'48'},
{countryName:'French Polynesia',countryCode:'689'},
{countryName:'Portugal',countryCode:'351'},
{countryName:'Puerto Rico',countryCode:'1787'},
{countryName:'Qatar',countryCode:'974'},
{countryName:'Reunion ',countryCode:'262'},
{countryName:'Romania',countryCode:'40'},
{countryName:'Russian',countryCode:'7'},
{countryName:'Saint Lucia',countryCode:'1758'},
{countryName:'Saint Vincent',countryCode:'1784'},
{countryName:'Samoa',countryCode:'684'},
{countryName:'Samoa',countryCode:'685'},
{countryName:'San Marino',countryCode:'378'},
{countryName:'Sao Tome and Principe',countryCode:'239'},
{countryName:'Saudi Arabia',countryCode:'966'},
{countryName:'Senegal',countryCode:'221'},
{countryName:'Seychelles',countryCode:'248'},
{countryName:'Sierra Leone',countryCode:'232'},
{countryName:'Singapore',countryCode:'65'},
{countryName:'Slovak',countryCode:'421'},
{countryName:'Slovenia',countryCode:'386'},
{countryName:'Solomon Islands',countryCode:'677'},
{countryName:'Somalia',countryCode:'252'},
{countryName:'South Africa',countryCode:'27'},
{countryName:'Spain',countryCode:'34'},
{countryName:'Sri Lanka',countryCode:'94'},
{countryName:'Saint Lucia',countryCode:'1758'},
{countryName:'Saint Vincent and the Grenadines',countryCode:'1784'},
{countryName:'Sudan',countryCode:'249'},
{countryName:'Suriname',countryCode:'597'},
{countryName:'Swaziland',countryCode:'268'},
{countryName:'Sweden',countryCode:'46'},
{countryName:'Switzerland',countryCode:'41'},
{countryName:'Syria',countryCode:'963'},
{countryName:'Taiwan',countryCode:'886'},
{countryName:'Tajikistan',countryCode:'992'},
{countryName:'Tanzania',countryCode:'255'},
{countryName:'Thailand',countryCode:'66'},
{countryName:'Togo',countryCode:'228'},
{countryName:'Tonga',countryCode:'676'},
{countryName:'Trinidad and Tobago',countryCode:'1809'},
{countryName:'Tunisia',countryCode:'216'},
{countryName:'Turkey',countryCode:'90'},
{countryName:'Turkmenistan',countryCode:'993'},
{countryName:'Uganda',countryCode:'256'},
{countryName:'Ukraine',countryCode:'380'},
{countryName:'United Arab Emirates',countryCode:'971'},
{countryName:'United Kingdom',countryCode:'44'},
{countryName:'United States',countryCode:'1'},
{countryName:'Uruguay',countryCode:'598'},
{countryName:'Uzbekistan',countryCode:'233'},
{countryName:'Venezuela',countryCode:'58'},
{countryName:'Viet Nam',countryCode:'84'},
{countryName:'Yemen',countryCode:'967'},
{countryName:'Yugoslavia',countryCode:'381'},
{countryName:'South Africa',countryCode:'27'},
{countryName:'Zimbabwe ',countryCode:'263'},
{countryName:'Zaire',countryCode:'243'},
{countryName:'Zambia',countryCode:'260'}
];

var error_msg = [
    {code:'10016',msg:' user does not exist '},
    {code:'10104',msg:' randcode error'},
    {code:'30315',msg:' Parameter error '},
    {code:'30501',msg:' Mailbox has been registered '},
    {code:'30502',msg:' Mailbox format error '},
    {code:'30504',msg:' Mail send fail '}
]

var error_str = "Error code:";

var mail_str="Mail";
var platform_str="platform";
var newpassword_notequest_confirmedpassword=" The new password is not consistent with the confirmed password ";
var not_null="Can't be empty!";
var lack_of_length="The password must be a combination of letters and numbers, and the length must be between 8-10 characters.";

